/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KeywordSearch */

#ifndef _Included_KeywordSearch
#define _Included_KeywordSearch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     KeywordSearch
 * Method:    startKeySearch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_KeywordSearch_startKeySearch
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
