/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FolderSearch */

#ifndef _Included_FolderSearch
#define _Included_FolderSearch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FolderSearch
 * Method:    startSearch
 * Signature: (Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_FolderSearch_startSearch
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
